apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- all-openshift-clusters-managedclustersetbinding.yaml
- all-openshift-clusters-managedclusterset.yaml
- all-openshift-clusters-placement.yaml
- argo-acm-importer-gitopscluster.yaml
- local-cluster-managedcluster.yaml
#- openshift-gitops-ns.yaml
